### ISSUE TITLE
Testing Could Be More Robust

### ISSUE THREAD

**Issue by dakotalillie** [learn-co-curriculum/playlister-static-generator-with-ar#10]
Hi,

I'd like to note that I was able to get all tests passing without totally fulfilling the instructions. The issue is that each of the tests are passing in only a single example... The show pages in particular are only testing for one artist/genre/song, rather than confirming to make sure there are show pages for multiple items. As such, I was able to get the tests passing using <item>.all.first, rather than by obtaining the specific instance from the binding information passed into the site generator from the invoking class. I'll be working to rectify this issue in my own code, but I figured it should be brought up and addressed for future students.

**Comment by maxwellbenton** [comment]
Hey @dakotalillie,

Thanks for opening this issue and providing feedback! We've updated the tests in lab to test create multiple model instances so that a solution involving `.all.first` will no longer work as a passing solution, which should resolve this issue.

Hope all is well, my friend!
