### ISSUE TITLE
Needs to be rewritten

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/playlister-static-generator-with-ar#2]
there are a lot of weird patterns in how this app is managed that make getting it to pass hard. plus the tests are vague. and there should be temp directories.

**Comment by AnnJohn** [comment]
Iceboxing the issue for now.

**Comment by jmburges** [comment]
hey @aviflombaum can you explain a bit more what you mean? some examples might help?

**Comment by aviflombaum** [comment]
Ya, some of the issues involve whether we pass locals or ivars to views, additionally, the db connection management is an anti-pattern, things like that. I can give more examples but I don't think this is pressing at the moment.

**Comment by pletcher** [comment]
I got rid of some of the weird stuff that was happening with db management. I left the custom `db` rake tasks alone for now, but we might want to circle back about those.

**Comment by sgharms** [comment]
@aviflombaum We've added this to the internal JIRA ticket CO-412 so that instead of having the request buried here we can slot it in as part of a project. Closing this as duplicative now.
